version: 0.1
phases:
  install:
    runtime-versions:
      java: openjdk8
      android: 28
  build:
    commands:
      - cd android && ./gradlew assembleRelease
artifacts:
  files:
    - android/app/build/outputs/apk/app-prod-release-unsigned.apk