export const LOAD_USER_START = 'LOAD_USER_START';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';
export const INPUT_TEXT = 'INPUT_TEXT';
export const RESET = 'RESET';
export const LOAD_SETTINGS_START = 'LOAD_SETTINGS_START';
export const LOAD_SETTINGS_SUCCESS = 'LOAD_SETTINGS_START';
export const LOAD_SETTINGS_FAIL = 'LOAD_SETTINGS_START';

//Lead Action types
export const LOAD_LEAD_START = 'LOAD_LEAD_START';
export const LOAD_LEAD_SUCCESS = 'LOAD_LEAD_SUCCESS';
export const LOAD_LEAD_FAIL = 'LOAD_LEAD_FAIL';
export const ADD_LEAD = 'ADD_LEAD';
export const FETCH_LEAD = 'FETCH_LEAD';
export const DELETE_LEAD = 'DELETE_LEAD';

//OTP Action types
export const LOAD_OTP_START = 'LOAD_OTP_START';
export const OTP_SENT = 'OTP_SENT';
export const LOAD_OTP_FAIL = 'LOAD_OTP_FAIL';
export const LOAD_OTP_INIT = 'LOAD_OTP_INIT';

//Campaign Actions
export const LOAD_CAMPAIGN_START = 'LOAD_CAMPAIGN_START';
export const LOAD_CAMPAIGN_SUCCESS = 'LOAD_CAMPAIGN_SUCCESS';
export const LOAD_CAMPAIGN_FAIL = 'LOAD_CAMPAIGN_FAIL';
export const FETCH_CAMPAIGN = 'FETCH_CAMPAIGN';
export const CAMPAIGN_SELECTED = 'CAMPAIGN_SELECTED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';



export const LOCATION_CAPTURE_START = 'LOCATION_CAPTURE_START';
export const LOCATION_CAPTURE_SUCCESS = 'LOCATION_CAPTURE_SUCCESS';
export const LOCATION_CAPTURE_FAILURE = 'LOCATION_CAPTURE_FAILURE';
