export const LOAD_USER_START = 'LOAD_USER_START';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';
export const INPUT_TEXT = 'INPUT_TEXT';
export const RESET = 'RESET';
export const LOAD_SETTINGS_START = 'LOAD_SETTINGS_START';
export const LOAD_SETTINGS_SUCCESS = 'LOAD_SETTINGS_START';
export const LOAD_SETTINGS_FAIL = 'LOAD_SETTINGS_START';

//Lead Action types
export const LOAD_LEAD_START = 'LOAD_LEAD_START';
export const LOAD_LEAD_SUCCESS = 'LOAD_LEAD_SUCCESS';
export const LOAD_LEAD_FAIL = 'LOAD_LEAD_FAIL';
export const ADD_LEAD = 'ADD_LEAD';
export const FETCH_LEAD = 'FETCH_LEAD';
export const DELETE_LEAD = 'DELETE_LEAD';
export const FETCH_BOARD = 'FETCH_BOARD';
export const FETCH_CLASSES = 'FETCH_CLASSES';
export const FETCH_STATES = 'FETCH_STATES';
export const META_DATA_ERROR = 'META_DATA_ERROR';
export const FETCH_COMPLETE = 'FETCH_COMPLETE';
export const FETCH_FILTERED_LEADS = 'FETCH_FILTERED_LEADS';
export const LEAD_RESET_ACTION = 'LEAD_RESET_ACTION';

//OTP Action types
export const LOAD_OTP_START = 'LOAD_OTP_START';
export const OTP_SENT = 'OTP_SENT';
export const OTP_VALIDATE = 'OTP_VALIDATE';
export const LOAD_OTP_FAIL = 'LOAD_OTP_FAIL';
export const LOAD_OTP_INIT = 'LOAD_OTP_INIT';

//Campaign Actions
export const LOAD_CAMPAIGN_START = 'LOAD_CAMPAIGN_START';
export const LOAD_CAMPAIGN_SUCCESS = 'LOAD_CAMPAIGN_SUCCESS';
export const LOAD_CAMPAIGN_FAIL = 'LOAD_CAMPAIGN_FAIL';
export const FETCH_CAMPAIGN = 'FETCH_CAMPAIGN';
export const CAMPAIGN_SELECTED = 'CAMPAIGN_SELECTED';
export const CAMPAIGN_SELECTED_ONLINE = 'CAMPAIGN_SELECTED_ONLINE';
export const CAMPAIGN_SELECTED_OFFLINE = 'CAMPAIGN_SELECTED_OFFLINE';
export const ATTENDANCE_UPDATE = 'ATTENDANCE_UPDATE';
export const SYNC_ATTENDANCE_SUCCESS = 'SYNC_ATTENDANCE_SUCCESS';
export const SYNC_ATTENDANCE_FAILURE = 'SYNC_ATTENDANCE_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

//Forgot Password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const FORGOT_PASSWORD_INIT = 'FORGOT_PASSWORD_INIT';

export const LOCATION_CAPTURE_START = 'LOCATION_CAPTURE_START';
export const LOCATION_CAPTURE_SUCCESS = 'LOCATION_CAPTURE_SUCCESS';
export const LOCATION_CAPTURE_FAILURE = 'LOCATION_CAPTURE_FAILURE';

export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS';

export const ADD_OFFLINE_LEAD = 'ADD_OFFLINE_LEAD';
export const FETCH_OFFLINE_LEAD = 'FETCH_OFFLINE_LEAD';
export const SYNC_OFFLINE_LEADS = 'SYNC_OFFLINE_LEADS';
export const DELETE_SYNCED_LEADS = 'DELETE_SYNCED_LEADS';

export const ERROR_CALL_ACTION = 'ERROR_CALL_ACTION';
export const SERVER_ERROR_CALL_ACTION = 'SERVER_ERROR_CALL_ACTION';
export const ERROR_CALL_RESET_ACTION = 'ERROR_CALL_RESET_ACTION';
export const FETCH_LEAD_REPORT = 'FETCH_LEAD_REPORT';
export const LEAD_REPORT_START = 'LEAD_REPORT_START';
export const LEAD_REPORT_FAIL = 'LEAD_REPORT_FAIL';
