version: 0.2
phases:
    install:
        runtime-versions:
            java: openjdk8
            android: 28
    pre_build:
        commands:
            - npm install
            - npx jetify
    build:
        commands:
            - ./gradlew assembleDebug
artifacts:
    files:
        - app/build/outputs/apk/app-debug-unsigned.apk
