version: 0.2 
phases: 
    install: 
        runtime-versions: 
            java: openjdk8 
            android: 28 
    build: 
        commands: 
            - ./gradlew assembleDebug 
artifacts: 
    files: 
        - android/app/build/outputs/apk/debug/app-debug-unsigned.apk