export const StorageConstants = {
    TOKEN_KEY: 'USER_TOKEN',
    USER: 'USER',
    USER_CAMPAIGNS: 'USER_CAMPAIGNS',
    SELECTED_CAMPAIGN: 'SELECTED_CAMPAIGN',
    USER_LEADS: 'USER_LEADS',
    USER_OTP: 'USER_OTP',
};
